export const enum SystemName {
  Restart = 'RESTART',
  Save = 'SAVE',
  Load = 'LOAD',
  NewGame = 'NEW GAME',
  QuitGame = 'QUIT GAME',
  LoadGame = 'LOAD GAME',
  Play = 'PLAY',
  SelectCheckers = 'SELECT CHECKERS',
  CheckersRu = 'RUSSIAN CHECKERS',
  Settings = 'SETTINGS',
  Settings2 = '⚙️',
  Help = 'HELP',
  Help2 = '❔',
  Back = 'BACK',
  Unit = 'UNIT',
}
